name: CI

on:
  push:
    branches: [master, main]

jobs:
  main:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: docker_rails_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y postgresql-client
          gem install bundler

      - name: Install gems
        run: |
          bundle install

      - name: Prepare database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: root
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare

      - name: Run rspec tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: root
          RAILS_ENV: test
        run: |
          bundle exec rspec
